#!/bin/sh

cd ~/.dotfiles && git pull --rebase origin sumologic

mkdir -p ~/.config/fish
ln -sfF ~/.dotfiles/init.fish ~/.config/omf/init.fish
ln -sfF ~/.dotfiles/sumo.fish ~/.config/fish/conf.d/sumo.fish
ln -sfF ~/.dotfiles/.screenrc ~/.screenrc
ln -sfF ~/.dotfiles/.tmux.conf ~/.tmux.conf
ln -sfF ~/.dotfiles/.gitconfig ~/.gitconfig
ln -sfF ~/.dotfiles/.bashrc ~/.bashrc
ln -sfF ~/.dotfiles/.ctags ~/.ctags
ln -sfF ~/.dotfiles/.inputrc ~/.inputrc
ln -sfF ~/.dotfiles/.editrc ~/.editrc
